# Generated by Django 6.0.7 on 2026-07-20 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='کد تجهیز')),
                ('name', models.CharField(max_length=255, verbose_name='نام تجهیز')),
                ('asset_type', models.CharField(choices=[('pump', 'پمپ'), ('motor', 'الکتروموتور'), ('compressor', 'کمپرسور'), ('tank', 'مخزن'), ('valve', 'شیرآلات'), ('fan', 'فن'), ('generator', 'ژنراتور'), ('transformer', 'ترانسفورماتور'), ('instrument', 'ابزار دقیق'), ('heat_exchanger', 'مبدل حرارتی'), ('boiler', 'دیگ بخار'), ('chiller', 'چیلر'), ('pipeline', 'خط لوله'), ('electrical_panel', 'تابلو برق'), ('other', 'سایر')], default='other', max_length=50, verbose_name='نوع تجهیز')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='سازنده')),
                ('model', models.CharField(blank=True, max_length=255, verbose_name='مدل')),
                ('serial_number', models.CharField(blank=True, max_length=255, verbose_name='شماره سریال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('commission_date', models.DateField(blank=True, null=True, verbose_name='تاریخ راه\u200cاندازی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'تجهیز',
                'verbose_name_plural': 'تجهیزات',
                'ordering': ['project', 'code'],
                'constraints': [models.UniqueConstraint(fields=('project', 'code'), name='unique_asset_code_per_project')],
            },
        ),
    ]
