# Generated by Django 6.0.7 on 2026-07-21 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('locations', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['project_id', 'code'], 'verbose_name': 'تجهیز', 'verbose_name_plural': 'تجهیزات'},
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='locations.location', verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('equipment', 'تجهیز'), ('machine', 'ماشین\u200cآلات'), ('electrical', 'تجهیز برقی'), ('instrument', 'ابزار دقیق'), ('vehicle', 'وسیله نقلیه'), ('building', 'ساختمان'), ('facility', 'تأسیسات'), ('tool', 'ابزار'), ('other', 'سایر')], default='equipment', max_length=30, verbose_name='نوع تجهیز'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='code',
            field=models.CharField(max_length=50, verbose_name='کد تجهیز'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='projects.project', verbose_name='پروژه'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['project', 'code'], name='asset_project_code_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['project', 'name'], name='asset_project_name_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['project', 'asset_type'], name='asset_project_type_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['project', 'is_active'], name='asset_project_active_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['location'], name='asset_location_idx'),
        ),
    ]
