# Generated by Django 6.0.7 on 2026-08-03 07:00

import decimal

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectNumberingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(blank=True, max_length=20)),
                ("separator", models.CharField(default="-", max_length=3)),
                ("next_number", models.PositiveBigIntegerField(default=1)),
                ("padding", models.PositiveSmallIntegerField(default=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_numbering_settings",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["organization_id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "برنامه‌ریزی‌شده"),
                            ("in_progress", "در حال اجرا"),
                            ("blocked", "مسدود"),
                            ("completed", "تکمیل‌شده"),
                            ("cancelled", "لغوشده"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=decimal.Decimal("1.000"),
                        max_digits=8,
                    ),
                ),
                ("planned_start", models.DateField(blank=True, null=True)),
                ("planned_end", models.DateField(blank=True, null=True)),
                ("actual_start", models.DateField(blank=True, null=True)),
                ("actual_end", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project_id", "order", "id"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"],
                        name="project_stage_status_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="projectnumberingsettings",
            constraint=models.UniqueConstraint(
                fields=("organization",),
                name="unique_project_numbering_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectstage",
            constraint=models.UniqueConstraint(
                fields=("project", "code"),
                name="unique_project_stage_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectstage",
            constraint=models.UniqueConstraint(
                condition=Q(is_active=True),
                fields=("project", "order"),
                name="unique_active_project_stage_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectstage",
            constraint=models.CheckConstraint(
                condition=Q(weight__gt=0),
                name="project_stage_weight_positive",
            ),
        ),
    ]
