# Generated by Django 6.0.7 on 2026-07-21 22:00

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_alter_asset_options_asset_location_and_more'),
        ('locations', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(max_length=50, verbose_name='شماره دستورکار')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دستورکار')),
                ('description', models.TextField(verbose_name='شرح کار')),
                ('maintenance_type', models.CharField(choices=[('corrective', 'تعمیرات اصلاحی'), ('preventive', 'نگهداری پیشگیرانه'), ('predictive', 'نگهداری پیش\u200cبینانه'), ('inspection', 'بازرسی'), ('lubrication', 'روانکاری'), ('calibration', 'کالیبراسیون'), ('installation', 'نصب و راه\u200cاندازی'), ('modification', 'اصلاح و بهبود'), ('safety', 'ایمنی'), ('general', 'عمومی')], default='corrective', max_length=30, verbose_name='نوع تعمیرات')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('normal', 'عادی'), ('high', 'زیاد'), ('urgent', 'فوری'), ('emergency', 'اضطراری')], default='normal', max_length=20, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('open', 'باز'), ('assigned', 'تخصیص\u200cیافته'), ('in_progress', 'در حال انجام'), ('on_hold', 'متوقف'), ('completed', 'تکمیل\u200cشده'), ('closed', 'بسته\u200cشده'), ('cancelled', 'لغوشده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('source', models.CharField(choices=[('manual', 'ثبت دستی'), ('work_request', 'درخواست تعمیرات'), ('preventive_maintenance', 'برنامه PM'), ('inspection', 'بازرسی'), ('condition_monitoring', 'پایش وضعیت'), ('breakdown', 'خرابی اضطراری'), ('other', 'سایر')], default='manual', max_length=30, verbose_name='منبع ایجاد')),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='شروع برنامه\u200cریزی\u200cشده')),
                ('planned_finish', models.DateTimeField(blank=True, null=True, verbose_name='پایان برنامه\u200cریزی\u200cشده')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='شروع واقعی')),
                ('actual_finish', models.DateTimeField(blank=True, null=True, verbose_name='پایان واقعی')),
                ('estimated_labor_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='ساعت کار برآوردی')),
                ('actual_labor_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='ساعت کار واقعی')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='هزینه برآوردی')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='هزینه واقعی')),
                ('production_stopped', models.BooleanField(default=False, verbose_name='توقف تولید')),
                ('permit_required', models.BooleanField(default=False, verbose_name='نیازمند مجوز کار')),
                ('lockout_tagout_required', models.BooleanField(default=False, verbose_name='نیازمند قفل و برچسب\u200cگذاری')),
                ('safety_notes', models.TextField(blank=True, verbose_name='نکات ایمنی')),
                ('work_performed', models.TextField(blank=True, verbose_name='شرح کار انجام\u200cشده')),
                ('completion_notes', models.TextField(blank=True, verbose_name='یادداشت تکمیل')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='دلیل لغو')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بسته\u200cشدن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='assets.asset', verbose_name='تجهیز')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='بسته\u200cشده توسط')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='تکمیل\u200cکننده')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='locations.location', verbose_name='موقعیت')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='projects.project', verbose_name='پروژه')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervised_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='سرپرست')),
            ],
            options={
                'verbose_name': 'دستورکار',
                'verbose_name_plural': 'دستورکارها',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_type', models.CharField(choices=[('mechanical', 'مکانیکی'), ('electrical', 'برقی'), ('instrumentation', 'ابزار دقیق'), ('hydraulic', 'هیدرولیک'), ('pneumatic', 'پنوماتیک'), ('process', 'فرایندی'), ('structural', 'سازه\u200cای'), ('software', 'نرم\u200cافزاری'), ('operational', 'بهره\u200cبرداری'), ('unknown', 'نامشخص'), ('other', 'سایر')], default='unknown', max_length=30, verbose_name='نوع خرابی')),
                ('failure_mode', models.CharField(blank=True, max_length=255, verbose_name='مد خرابی')),
                ('symptom', models.TextField(blank=True, verbose_name='نشانه خرابی')),
                ('immediate_cause', models.TextField(blank=True, verbose_name='علت مستقیم')),
                ('root_cause', models.TextField(blank=True, verbose_name='علت ریشه\u200cای')),
                ('corrective_action', models.TextField(blank=True, verbose_name='اقدام اصلاحی')),
                ('preventive_action', models.TextField(blank=True, verbose_name='اقدام پیشگیرانه')),
                ('requires_follow_up', models.BooleanField(default=False, verbose_name='نیازمند پیگیری')),
                ('follow_up_due_date', models.DateField(blank=True, null=True, verbose_name='مهلت پیگیری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='failure', to='work_orders.workorder', verbose_name='دستورکار')),
            ],
            options={
                'verbose_name': 'تحلیل خرابی',
                'verbose_name_plural': 'تحلیل\u200cهای خرابی',
            },
        ),
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=50, verbose_name='شماره درخواست')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان درخواست')),
                ('description', models.TextField(verbose_name='شرح درخواست')),
                ('maintenance_type', models.CharField(choices=[('corrective', 'تعمیرات اصلاحی'), ('preventive', 'نگهداری پیشگیرانه'), ('predictive', 'نگهداری پیش\u200cبینانه'), ('inspection', 'بازرسی'), ('lubrication', 'روانکاری'), ('calibration', 'کالیبراسیون'), ('installation', 'نصب و راه\u200cاندازی'), ('modification', 'اصلاح و بهبود'), ('safety', 'ایمنی'), ('general', 'عمومی')], default='corrective', max_length=30, verbose_name='نوع تعمیرات')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('normal', 'عادی'), ('high', 'زیاد'), ('urgent', 'فوری'), ('emergency', 'اضطراری')], default='normal', max_length=20, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ثبت\u200cشده'), ('under_review', 'در حال بررسی'), ('approved', 'تأییدشده'), ('rejected', 'ردشده'), ('converted', 'تبدیل\u200cشده به دستورکار'), ('cancelled', 'لغوشده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان درخواست')),
                ('required_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ موردنیاز')),
                ('failure_observed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان مشاهده خرابی')),
                ('production_stopped', models.BooleanField(default=False, verbose_name='توقف تولید')),
                ('safety_risk', models.BooleanField(default=False, verbose_name='دارای ریسک ایمنی')),
                ('environmental_risk', models.BooleanField(default=False, verbose_name='دارای ریسک زیست\u200cمحیطی')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی')),
                ('review_notes', models.TextField(blank=True, verbose_name='یادداشت بررسی')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='دلیل رد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_requests', to='assets.asset', verbose_name='تجهیز')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_requests', to='locations.location', verbose_name='موقعیت')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_requests', to='projects.project', verbose_name='پروژه')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_work_requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cکننده')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_work_requests', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
            ],
            options={
                'verbose_name': 'درخواست تعمیرات',
                'verbose_name_plural': 'درخواست\u200cهای تعمیرات',
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='work_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_order', to='work_orders.workrequest', verbose_name='درخواست تعمیرات'),
        ),
        migrations.CreateModel(
            name='WorkOrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('supervisor', 'سرپرست'), ('technician', 'تکنسین'), ('engineer', 'مهندس'), ('inspector', 'بازرس'), ('contractor', 'پیمانکار'), ('helper', 'کمک\u200cکار'), ('other', 'سایر')], default='technician', max_length=20, verbose_name='نقش')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان تخصیص')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان حذف تخصیص')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_work_order_assignments', to=settings.AUTH_USER_MODEL, verbose_name='تخصیص\u200cدهنده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_assignments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='work_orders.workorder', verbose_name='دستورکار')),
            ],
            options={
                'verbose_name': 'تخصیص دستورکار',
                'verbose_name_plural': 'تخصیص\u200cهای دستورکار',
                'ordering': ['-assigned_at', '-id'],
                'indexes': [models.Index(fields=['work_order', 'is_active'], name='woa_order_active_idx'), models.Index(fields=['user', 'is_active'], name='woa_user_active_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('work_order', 'user', 'role'), name='unique_active_work_order_assignment')],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderDowntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='شروع توقف')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان توقف')),
                ('production_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='میزان افت تولید')),
                ('reason', models.TextField(blank=True, verbose_name='علت توقف')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtime_entries', to='work_orders.workorder', verbose_name='دستورکار')),
            ],
            options={
                'verbose_name': 'توقف تجهیز',
                'verbose_name_plural': 'توقف\u200cهای تجهیز',
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['work_order', 'started_at'], name='wod_order_start_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('production_loss__gte', 0)), name='wod_production_loss_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاریخ کار')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='ساعات کار')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='نرخ ساعتی')),
                ('description', models.TextField(blank=True, verbose_name='شرح فعالیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_labor_entries', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_entries', to='work_orders.workorder', verbose_name='دستورکار')),
            ],
            options={
                'verbose_name': 'کارکرد نیروی انسانی',
                'verbose_name_plural': 'کارکردهای نیروی انسانی',
                'ordering': ['-work_date', '-id'],
                'indexes': [models.Index(fields=['work_order', 'work_date'], name='wol_order_date_idx'), models.Index(fields=['user', 'work_date'], name='wol_user_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('hours__gte', 0)), name='wol_hours_nonnegative'), models.CheckConstraint(condition=models.Q(('hourly_rate__gte', 0)), name='wol_hourly_rate_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('draft', 'پیش\u200cنویس'), ('open', 'باز'), ('assigned', 'تخصیص\u200cیافته'), ('in_progress', 'در حال انجام'), ('on_hold', 'متوقف'), ('completed', 'تکمیل\u200cشده'), ('closed', 'بسته\u200cشده'), ('cancelled', 'لغوشده')], max_length=20, verbose_name='وضعیت قبلی')),
                ('new_status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('open', 'باز'), ('assigned', 'تخصیص\u200cیافته'), ('in_progress', 'در حال انجام'), ('on_hold', 'متوقف'), ('completed', 'تکمیل\u200cشده'), ('closed', 'بسته\u200cشده'), ('cancelled', 'لغوشده')], max_length=20, verbose_name='وضعیت جدید')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان تغییر')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='تغییردهنده')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='work_orders.workorder', verbose_name='دستورکار')),
            ],
            options={
                'verbose_name': 'تاریخچه وضعیت دستورکار',
                'verbose_name_plural': 'تاریخچه وضعیت دستورکارها',
                'ordering': ['-changed_at', '-id'],
                'indexes': [models.Index(fields=['work_order', 'changed_at'], name='wosh_order_changed_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workrequest',
            index=models.Index(fields=['project', 'request_number'], name='wr_project_number_idx'),
        ),
        migrations.AddIndex(
            model_name='workrequest',
            index=models.Index(fields=['project', 'status'], name='wr_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workrequest',
            index=models.Index(fields=['project', 'priority'], name='wr_project_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='workrequest',
            index=models.Index(fields=['asset', 'status'], name='wr_asset_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workrequest',
            index=models.Index(fields=['requested_by', 'status'], name='wr_requester_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workrequest',
            index=models.Index(fields=['requested_at'], name='wr_requested_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='workrequest',
            constraint=models.UniqueConstraint(fields=('project', 'request_number'), name='unique_work_request_number_per_project'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['project', 'work_order_number'], name='wo_project_number_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['project', 'status'], name='wo_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['project', 'priority'], name='wo_project_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['asset', 'status'], name='wo_asset_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['supervisor', 'status'], name='wo_supervisor_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['planned_start'], name='wo_planned_start_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['actual_start'], name='wo_actual_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(fields=('project', 'work_order_number'), name='unique_work_order_number_per_project'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_labor_hours__gte', 0)), name='wo_estimated_labor_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(('actual_labor_hours__gte', 0)), name='wo_actual_labor_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_cost__gte', 0)), name='wo_estimated_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(('actual_cost__gte', 0)), name='wo_actual_cost_nonnegative'),
        ),
    ]
