# Generated by Django 6.0.7 on 2026-07-21 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('site', 'Site'), ('area', 'Area'), ('plant', 'Plant'), ('building', 'Building'), ('floor', 'Floor'), ('room', 'Room'), ('line', 'Production Line'), ('section', 'Section'), ('unit', 'Unit'), ('warehouse', 'Warehouse'), ('yard', 'Yard'), ('other', 'Other')], default='area', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='locations.location')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='projects.project')),
            ],
            options={
                'ordering': ['project_id', 'code'],
                'indexes': [models.Index(fields=['project', 'code'], name='locations_l_project_c5e210_idx'), models.Index(fields=['project', 'name'], name='locations_l_project_869cce_idx'), models.Index(fields=['project', 'location_type'], name='locations_l_project_0a3a83_idx'), models.Index(fields=['project', 'is_active'], name='locations_l_project_ff6b07_idx'), models.Index(fields=['parent'], name='locations_l_parent__2d4346_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'code'), name='unique_location_code_per_project'), models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='location_parent_cannot_be_self')],
            },
        ),
    ]
