# Generated by Django 6.0.7 on 2026-07-24 08:55

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('work_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, verbose_name='کد کالا')),
                ('name', models.CharField(max_length=255, verbose_name='نام کالا')),
                ('item_type', models.CharField(choices=[('spare_part', 'قطعه یدکی'), ('consumable', 'کالای مصرفی'), ('tool', 'ابزار'), ('lubricant', 'روانکار'), ('safety', 'تجهیزات ایمنی'), ('electrical', 'کالای برقی'), ('mechanical', 'کالای مکانیکی'), ('instrumentation', 'ابزار دقیق'), ('raw_material', 'مواد اولیه'), ('other', 'سایر')], default='spare_part', max_length=30, verbose_name='نوع کالا')),
                ('category', models.CharField(blank=True, max_length=150, verbose_name='گروه کالا')),
                ('unit_of_measure', models.CharField(choices=[('each', 'عدد'), ('piece', 'قطعه'), ('set', 'ست'), ('pair', 'جفت'), ('box', 'جعبه'), ('pack', 'بسته'), ('kg', 'کیلوگرم'), ('g', 'گرم'), ('ton', 'تن'), ('l', 'لیتر'), ('ml', 'میلی\u200cلیتر'), ('m', 'متر'), ('cm', 'سانتی\u200cمتر'), ('mm', 'میلی\u200cمتر'), ('m2', 'مترمربع'), ('m3', 'مترمکعب'), ('roll', 'رول'), ('sheet', 'ورق'), ('other', 'سایر')], default='each', max_length=20, verbose_name='واحد اندازه\u200cگیری')),
                ('manufacturer', models.CharField(blank=True, max_length=150, verbose_name='سازنده')),
                ('part_number', models.CharField(blank=True, max_length=150, verbose_name='شماره قطعه')),
                ('manufacturer_part_number', models.CharField(blank=True, max_length=150, verbose_name='شماره قطعه سازنده')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16, verbose_name='حداقل موجودی')),
                ('maximum_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16, verbose_name='حداکثر موجودی')),
                ('reorder_point', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16, verbose_name='نقطه سفارش')),
                ('standard_unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='بهای استاندارد واحد')),
                ('is_critical', models.BooleanField(default=False, verbose_name='قطعه بحرانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
                'ordering': ['project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='کد انبار')),
                ('name', models.CharField(max_length=200, verbose_name='نام انبار')),
                ('warehouse_type', models.CharField(choices=[('main', 'انبار اصلی'), ('spare_parts', 'انبار قطعات یدکی'), ('tools', 'انبار ابزار'), ('consumables', 'انبار اقلام مصرفی'), ('temporary', 'انبار موقت'), ('quarantine', 'انبار قرنطینه'), ('scrap', 'انبار ضایعات'), ('other', 'سایر')], default='spare_parts', max_length=30, verbose_name='نوع انبار')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='مسئول انبار')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبارها',
                'ordering': ['project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18, verbose_name='موجودی فیزیکی')),
                ('reserved_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18, verbose_name='موجودی رزروشده')),
                ('average_unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='میانگین بهای واحد')),
                ('last_transaction_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان آخرین تراکنش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='inventory.inventoryitem', verbose_name='کالا')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='inventory.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'موجودی انبار',
                'verbose_name_plural': 'موجودی\u200cهای انبار',
                'ordering': ['warehouse', 'item'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18, verbose_name='مقدار درخواستی')),
                ('reserved_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18, verbose_name='مقدار رزروشده')),
                ('issued_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18, verbose_name='مقدار تحویل\u200cشده')),
                ('consumed_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18, verbose_name='مقدار مصرف\u200cشده')),
                ('returned_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18, verbose_name='مقدار برگشتی')),
                ('estimated_unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='بهای برآوردی واحد')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_parts', to='inventory.inventoryitem', verbose_name='کالا')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_order_parts', to='inventory.warehouse', verbose_name='انبار تأمین\u200cکننده')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_parts', to='work_orders.workorder', verbose_name='دستورکار')),
            ],
            options={
                'verbose_name': 'قطعه دستورکار',
                'verbose_name_plural': 'قطعات دستورکار',
                'ordering': ['work_order', 'item'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('receipt', 'رسید انبار'), ('issue', 'حواله خروج'), ('return', 'برگشت به انبار'), ('adjustment_in', 'اصلاح افزایشی'), ('adjustment_out', 'اصلاح کاهشی'), ('transfer_in', 'انتقال ورودی'), ('transfer_out', 'انتقال خروجی'), ('reservation', 'رزرو موجودی'), ('reservation_release', 'آزادسازی رزرو'), ('consumption', 'مصرف قطعه')], max_length=30, verbose_name='نوع تراکنش')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='مقدار')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='بهای واحد')),
                ('balance_after', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='موجودی پس از تراکنش')),
                ('reserved_balance_after', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='رزرو پس از تراکنش')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='شماره مرجع')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان تراکنش')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('is_void', models.BooleanField(default=False, verbose_name='باطل\u200cشده')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ابطال')),
                ('void_reason', models.TextField(blank=True, verbose_name='دلیل ابطال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='inventory.inventoryitem', verbose_name='کالا')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_stock_transactions', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده تراکنش')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='projects.project', verbose_name='پروژه')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_stock_transactions', to=settings.AUTH_USER_MODEL, verbose_name='باطل\u200cکننده')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='work_orders.workorder', verbose_name='دستورکار')),
                ('counterpart_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counterpart_stock_transactions', to='inventory.warehouse', verbose_name='انبار مقابل')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='inventory.warehouse', verbose_name='انبار')),
                ('work_order_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='inventory.workorderpart', verbose_name='قطعه دستورکار')),
            ],
            options={
                'verbose_name': 'تراکنش انبار',
                'verbose_name_plural': 'تراکنش\u200cهای انبار',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['project', 'code'], name='inv_item_project_code_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['project', 'item_type'], name='inv_item_project_type_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['project', 'is_active'], name='inv_item_project_active_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['manufacturer', 'part_number'], name='inv_item_mfr_part_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='unique_inventory_item_code_per_project'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_stock__gte', 0)), name='inv_item_min_stock_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_stock__gte', 0)), name='inv_item_max_stock_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('reorder_point__gte', 0)), name='inv_item_reorder_point_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('standard_unit_cost__gte', 0)), name='inv_item_unit_cost_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['project', 'code'], name='inv_wh_project_code_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['project', 'is_active'], name='inv_wh_project_active_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['warehouse_type', 'is_active'], name='inv_wh_type_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='unique_warehouse_code_per_project'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['warehouse', 'item'], name='inv_bal_wh_item_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['item', 'quantity_on_hand'], name='inv_bal_item_qty_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('warehouse', 'item'), name='unique_stock_balance_per_warehouse_item'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', 0)), name='inv_bal_on_hand_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0)), name='inv_bal_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('quantity_on_hand'))), name='inv_bal_reserved_not_above_stock'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('average_unit_cost__gte', 0)), name='inv_bal_avg_cost_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='workorderpart',
            index=models.Index(fields=['work_order', 'item'], name='inv_wop_order_item_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderpart',
            index=models.Index(fields=['warehouse', 'item'], name='inv_wop_wh_item_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorderpart',
            constraint=models.UniqueConstraint(fields=('work_order', 'item', 'warehouse'), name='unique_work_order_item_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='workorderpart',
            constraint=models.CheckConstraint(condition=models.Q(('requested_quantity__gt', 0)), name='inv_wop_requested_positive'),
        ),
        migrations.AddConstraint(
            model_name='workorderpart',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0)), name='inv_wop_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='workorderpart',
            constraint=models.CheckConstraint(condition=models.Q(('issued_quantity__gte', 0)), name='inv_wop_issued_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='workorderpart',
            constraint=models.CheckConstraint(condition=models.Q(('consumed_quantity__gte', 0)), name='inv_wop_consumed_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='workorderpart',
            constraint=models.CheckConstraint(condition=models.Q(('returned_quantity__gte', 0)), name='inv_wop_returned_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='workorderpart',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_unit_cost__gte', 0)), name='inv_wop_est_cost_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['project', 'occurred_at'], name='inv_tx_project_time_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['warehouse', 'item', 'occurred_at'], name='inv_tx_wh_item_time_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transaction_type', 'occurred_at'], name='inv_tx_type_time_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['work_order', 'occurred_at'], name='inv_tx_order_time_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['reference_number'], name='inv_tx_reference_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inv_tx_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='inv_tx_unit_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after__isnull', True), ('balance_after__gte', 0), _connector='OR'), name='inv_tx_balance_after_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_balance_after__isnull', True), ('reserved_balance_after__gte', 0), _connector='OR'), name='inv_tx_reserved_after_nonnegative'),
        ),
    ]
