# Generated by Django 6.0.7 on 2026-07-23 22:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_alter_asset_options_asset_location_and_more'),
        ('locations', '0001_initial'),
        ('projects', '0001_initial'),
        ('work_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventiveMaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_number', models.CharField(max_length=50, verbose_name='شماره برنامه')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان برنامه')),
                ('description', models.TextField(blank=True, verbose_name='شرح برنامه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('suspended', 'معلق'), ('completed', 'تکمیل\u200cشده'), ('cancelled', 'لغوشده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت')),
                ('maintenance_type', models.CharField(choices=[('corrective', 'تعمیرات اصلاحی'), ('preventive', 'نگهداری پیشگیرانه'), ('predictive', 'نگهداری پیش\u200cبینانه'), ('inspection', 'بازرسی'), ('lubrication', 'روانکاری'), ('calibration', 'کالیبراسیون'), ('installation', 'نصب و راه\u200cاندازی'), ('modification', 'اصلاح و بهبود'), ('safety', 'ایمنی'), ('general', 'عمومی')], default='preventive', max_length=30, verbose_name='نوع نگهداری')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('normal', 'عادی'), ('high', 'زیاد'), ('urgent', 'فوری'), ('emergency', 'اضطراری')], db_index=True, default='normal', max_length=20, verbose_name='اولویت')),
                ('frequency', models.CharField(choices=[('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('quarterly', 'سه\u200cماهه'), ('semiannual', 'شش\u200cماهه'), ('annual', 'سالانه'), ('custom_days', 'تعداد روز سفارشی')], default='monthly', max_length=20, verbose_name='تناوب')),
                ('custom_interval_days', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='فاصله سفارشی برحسب روز')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('last_due_date', models.DateField(blank=True, null=True, verbose_name='آخرین سررسید')),
                ('next_due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='سررسید بعدی')),
                ('generation_lead_days', models.PositiveIntegerField(default=7, verbose_name='تعداد روز تولید قبل از سررسید')),
                ('auto_generate_work_order', models.BooleanField(default=True, verbose_name='تولید خودکار دستورکار')),
                ('allow_duplicate_open_orders', models.BooleanField(default=False, verbose_name='اجازه ایجاد دستورکار باز تکراری')),
                ('estimated_duration_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='مدت تخمینی برحسب ساعت')),
                ('estimated_labor_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='ساعت کار تخمینی')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='هزینه تخمینی')),
                ('safety_instructions', models.TextField(blank=True, verbose_name='دستورالعمل\u200cهای ایمنی')),
                ('required_tools', models.TextField(blank=True, verbose_name='ابزارهای موردنیاز')),
                ('required_materials', models.TextField(blank=True, verbose_name='مواد و قطعات موردنیاز')),
                ('permit_required', models.BooleanField(default=False, verbose_name='نیازمند مجوز کار')),
                ('lockout_tagout_required', models.BooleanField(default=False, verbose_name='نیازمند قفل و برچسب\u200cگذاری')),
                ('production_stop_required', models.BooleanField(default=False, verbose_name='نیازمند توقف تولید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preventive_maintenance_plans', to='assets.asset', verbose_name='تجهیز')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_preventive_maintenance_plans', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preventive_maintenance_plans', to='locations.location', verbose_name='موقعیت')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventive_maintenance_plans', to='projects.project', verbose_name='پروژه')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_preventive_maintenance_plans', to=settings.AUTH_USER_MODEL, verbose_name='سرپرست')),
            ],
            options={
                'verbose_name': 'برنامه نگهداری پیشگیرانه',
                'verbose_name_plural': 'برنامه\u200cهای نگهداری پیشگیرانه',
                'ordering': ['next_due_date', 'plan_number'],
            },
        ),
        migrations.CreateModel(
            name='PreventiveMaintenanceGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(db_index=True, verbose_name='تاریخ سررسید')),
                ('scheduled_generation_date', models.DateField(verbose_name='تاریخ برنامه\u200cریزی\u200cشده تولید')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('generated', 'تولیدشده'), ('skipped', 'ردشده'), ('failed', 'ناموفق')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت تولید')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تولید')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_preventive_maintenance_orders', to=settings.AUTH_USER_MODEL, verbose_name='تولیدکننده')),
                ('work_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preventive_maintenance_generation', to='work_orders.workorder', verbose_name='دستورکار تولیدشده')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='preventive_maintenance.preventivemaintenanceplan', verbose_name='برنامه نگهداری')),
            ],
            options={
                'verbose_name': 'سابقه تولید دستورکار پیشگیرانه',
                'verbose_name_plural': 'سوابق تولید دستورکارهای پیشگیرانه',
                'ordering': ['-due_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PreventiveMaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('task_type', models.CharField(choices=[('inspection', 'بازرسی'), ('lubrication', 'روان\u200cکاری'), ('cleaning', 'تمیزکاری'), ('adjustment', 'تنظیم'), ('replacement', 'تعویض'), ('calibration', 'کالیبراسیون'), ('testing', 'آزمایش'), ('measurement', 'اندازه\u200cگیری'), ('tightening', 'سفت\u200cکاری'), ('general', 'عمومی')], default='general', max_length=20, verbose_name='نوع فعالیت')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فعالیت')),
                ('description', models.TextField(blank=True, verbose_name='شرح فعالیت')),
                ('acceptance_criteria', models.TextField(blank=True, verbose_name='معیار پذیرش')),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=0, verbose_name='مدت تخمینی برحسب دقیقه')),
                ('requires_shutdown', models.BooleanField(default=False, verbose_name='نیازمند توقف تجهیز')),
                ('requires_photo', models.BooleanField(default=False, verbose_name='نیازمند ثبت تصویر')),
                ('requires_measurement', models.BooleanField(default=False, verbose_name='نیازمند ثبت اندازه\u200cگیری')),
                ('measurement_unit', models.CharField(blank=True, max_length=50, verbose_name='واحد اندازه\u200cگیری')),
                ('minimum_acceptable_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='حداقل مقدار قابل\u200cقبول')),
                ('maximum_acceptable_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='حداکثر مقدار قابل\u200cقبول')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='الزامی')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='preventive_maintenance.preventivemaintenanceplan', verbose_name='برنامه نگهداری')),
            ],
            options={
                'verbose_name': 'فعالیت نگهداری پیشگیرانه',
                'verbose_name_plural': 'فعالیت\u200cهای نگهداری پیشگیرانه',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PreventiveMaintenanceTaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='انجام\u200cشده')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انجام')),
                ('measured_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='مقدار اندازه\u200cگیری\u200cشده')),
                ('result_is_acceptable', models.BooleanField(blank=True, null=True, verbose_name='نتیجه قابل\u200cقبول')),
                ('result_notes', models.TextField(blank=True, verbose_name='یادداشت نتیجه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_preventive_maintenance_tasks', to=settings.AUTH_USER_MODEL, verbose_name='انجام\u200cدهنده')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_results', to='preventive_maintenance.preventivemaintenancegeneration', verbose_name='سابقه تولید')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='preventive_maintenance.preventivemaintenancetask', verbose_name='فعالیت')),
            ],
            options={
                'verbose_name': 'نتیجه فعالیت نگهداری',
                'verbose_name_plural': 'نتایج فعالیت\u200cهای نگهداری',
                'ordering': ['task__sequence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='preventivemaintenanceplan',
            index=models.Index(fields=['project', 'status'], name='pm_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivemaintenanceplan',
            index=models.Index(fields=['project', 'plan_number'], name='pm_project_number_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivemaintenanceplan',
            index=models.Index(fields=['asset', 'status'], name='pm_asset_status_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivemaintenanceplan',
            index=models.Index(fields=['next_due_date', 'status'], name='pm_due_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='preventivemaintenanceplan',
            constraint=models.UniqueConstraint(fields=('project', 'plan_number'), name='unique_pm_plan_number_per_project'),
        ),
        migrations.AddConstraint(
            model_name='preventivemaintenanceplan',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='pm_end_date_after_start_date'),
        ),
        migrations.AddConstraint(
            model_name='preventivemaintenanceplan',
            constraint=models.CheckConstraint(condition=models.Q(('generation_lead_days__gte', 0)), name='pm_generation_lead_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='preventivemaintenanceplan',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_duration_hours__gte', 0)), name='pm_duration_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='preventivemaintenanceplan',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_labor_hours__gte', 0)), name='pm_labor_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='preventivemaintenanceplan',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_cost__gte', 0)), name='pm_cost_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='preventivemaintenancegeneration',
            index=models.Index(fields=['status', 'scheduled_generation_date'], name='pm_gen_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivemaintenancegeneration',
            index=models.Index(fields=['plan', 'due_date'], name='pm_gen_plan_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='preventivemaintenancegeneration',
            constraint=models.UniqueConstraint(fields=('plan', 'due_date'), name='unique_pm_generation_per_due_date'),
        ),
        migrations.AddIndex(
            model_name='preventivemaintenancetask',
            index=models.Index(fields=['plan', 'sequence'], name='pm_task_plan_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivemaintenancetask',
            index=models.Index(fields=['plan', 'is_active'], name='pm_task_plan_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='preventivemaintenancetask',
            constraint=models.UniqueConstraint(fields=('plan', 'sequence'), name='unique_pm_task_sequence_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='preventivemaintenancetask',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_duration_minutes__gte', 0)), name='pm_task_duration_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='preventivemaintenancetask',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_acceptable_value__isnull', True), ('maximum_acceptable_value__isnull', True), ('maximum_acceptable_value__gte', models.F('minimum_acceptable_value')), _connector='OR'), name='pm_task_max_value_gte_min_value'),
        ),
        migrations.AddIndex(
            model_name='preventivemaintenancetaskresult',
            index=models.Index(fields=['generation', 'is_completed'], name='pm_result_gen_done_idx'),
        ),
        migrations.AddConstraint(
            model_name='preventivemaintenancetaskresult',
            constraint=models.UniqueConstraint(fields=('generation', 'task'), name='unique_pm_task_result_per_generation'),
        ),
    ]
