# Generated by Django 6.0.7 on 2026-07-21 19:09

import asset_documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان سند')),
                ('document_type', models.CharField(choices=[('manual', 'راهنمای فنی'), ('datasheet', 'دیتاشیت'), ('drawing', 'نقشه'), ('certificate', 'گواهی\u200cنامه'), ('test_report', 'گزارش آزمون'), ('inspection_report', 'گزارش بازرسی'), ('photo', 'تصویر'), ('warranty', 'ضمانت\u200cنامه'), ('purchase_document', 'سند خرید'), ('commissioning', 'سند راه\u200cاندازی'), ('maintenance', 'سند نگهداری و تعمیرات'), ('other', 'سایر')], default='other', max_length=50, verbose_name='نوع سند')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='شماره سند')),
                ('revision', models.CharField(blank=True, max_length=50, verbose_name='ویرایش')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سند')),
                ('file', models.FileField(upload_to=asset_documents.models.asset_document_upload_path, verbose_name='فایل')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assets.asset', verbose_name='تجهیز')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_asset_documents', to=settings.AUTH_USER_MODEL, verbose_name='بارگذاری\u200cکننده')),
            ],
            options={
                'verbose_name': 'سند تجهیز',
                'verbose_name_plural': 'اسناد تجهیزات',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('document_number', ''), _negated=True), fields=('asset', 'document_number', 'revision'), name='unique_asset_document_number_revision')],
            },
        ),
    ]
